import checkbox from "../assets/Interface.svg";
const dashboardData = [
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Payment",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Successful",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Interest",
    Time: "1:10pm",
    Amount: "5000",
    Status: "Successful",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Interest",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Reversed",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Interest",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Failed",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Payment",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Successful",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Payment",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Failed",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Interest",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Successful",
  },
  {
    image: checkbox,
    Date: "2023-05-03",
    Description: "Debited from bank",
    Info: "Payment",
    Time: "1:10pm",
    Amount: "50,000",
    Status: "Successful",
  },
];
export default dashboardData;
